definitions:
  app.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
  app_service.AppParam:
    properties:
      android_version_code:
        type: string
      android_version_name:
        type: string
      app_name:
        type: string
      app_version_code:
        type: string
      app_version_name:
        type: string
      channel_code:
        type: string
      cpu_arch:
        type: string
      device_model:
        type: string
      device_no:
        type: string
      language:
        type: string
      resolution:
        type: string
      sdk_name:
        type: string
      sdk_version_code:
        type: string
      sdk_version_name:
        type: string
      storage_space:
        type: string
    required:
    - android_version_code
    - android_version_name
    - channel_code
    - cpu_arch
    - device_model
    - device_no
    - sdk_name
    - sdk_version_name
    - storage_space
    type: object
  gredis.Asset:
    properties:
      act_long_movie_url:
        description: 长视频 url
        type: string
      act_open_apps:
        description: 需要下载打开的应用  （json）
        type: string
      act_pop_time:
        description: 二维码自动弹出时间，单位：秒
        type: integer
      act_qrcode_bg_url:
        description: 二维码背景图url
        type: string
      act_qrcode_org_url:
        description: 二维码原链接url
        type: string
      act_qrcode_url:
        description: 二维码地址
        type: string
      act_toast:
        description: OK键引导文案
        type: string
      act_type:
        description: OK键动作类型 1-无动作 2-打开/下载应用 3-弹出二维码 4-加载长视频
        type: integer
      cover_url:
        description: 封面图地址
        type: string
      duration_end_date:
        description: 资源有效期 - 结束时间
        type: string
      duration_start_date:
        description: 资源有效期 - 开始时间
        type: string
      id:
        type: integer
      is_del:
        type: integer
      last_update_time:
        description: 最后更新时间 - 排序使用
        type: string
      movie_url:
        description: 视频地址
        type: string
      name:
        description: 名称
        type: string
      pic_urls:
        description: 多张图片url  （json）
        type: string
      remark:
        description: 描述
        type: string
      score:
        description: 评分
        type: number
      shelf_status:
        description: 上架状态 1-未上架 2-已上架 3-已下架
        type: integer
      type:
        description: 类型 1-视频 2-图片
        type: integer
      view_cities:
        description: 地区限制 （json）
        type: string
      view_limit:
        description: 青少年观影限制 0  - 不限制 1 – 限制
        type: integer
      view_tags:
        description: 数据标签 （json）
        type: string
    required:
    - act_long_movie_url
    - act_open_apps
    - act_pop_time
    - act_qrcode_bg_url
    - act_qrcode_org_url
    - act_qrcode_url
    - act_toast
    - act_type
    - cover_url
    - duration_end_date
    - duration_start_date
    - id
    - last_update_time
    - movie_url
    - name
    - pic_urls
    - remark
    - score
    - shelf_status
    - type
    type: object
  gredis.TrailerListParam:
    properties:
      channel_code:
        type: string
      device_no:
        type: string
      page:
        example: 1
        type: integer
      page_size:
        example: 20
        type: integer
    required:
    - channel_code
    - device_no
    - page
    type: object
  stats_service.Device:
    properties:
      android_version_code:
        type: string
      android_version_name:
        type: string
      app_name:
        type: string
      app_version_code:
        type: string
      app_version_name:
        type: string
      channel_code:
        type: string
      device_model:
        type: string
      device_name:
        type: string
      device_no:
        type: string
      device_vendor:
        type: string
      ip:
        type: string
      resolution:
        type: string
    required:
    - android_version_code
    - android_version_name
    - app_name
    - app_version_code
    - app_version_name
    - channel_code
    - device_model
    - device_name
    - device_no
    - device_vendor
    - ip
    - resolution
    type: object
  stats_service.SdkError:
    properties:
      app_name:
        type: string
      app_version_code:
        type: string
      app_version_name:
        type: string
      channel_code:
        type: string
      crash_log:
        type: string
      crash_time:
        type: string
      device_no:
        type: string
      ext:
        type: string
      sdk_name:
        type: string
      sdk_version_code:
        type: string
      sdk_version_name:
        type: string
      user_id:
        type: integer
    required:
    - app_name
    - app_version_code
    - app_version_name
    - channel_code
    - crash_log
    - crash_time
    - device_no
    - sdk_name
    - sdk_version_code
    - sdk_version_name
    type: object
  stats_service.SdkEvent:
    properties:
      app_name:
        type: string
      app_version_code:
        type: string
      app_version_name:
        type: string
      channel_code:
        type: string
      client_time:
        type: string
      device_brand:
        type: string
      device_model:
        type: string
      device_no:
        type: string
      event_kv_json:
        type: string
      event_name:
        type: string
      imei:
        type: string
      ip:
        type: string
      net_type:
        type: string
      newevent_type:
        type: integer
      newpuid:
        description: "IDFA \t\t\t\t\t\tstring `json:\"idfa\" `"
        type: string
      newsession_id:
        type: string
      os_version_code:
        type: string
      os_version_name:
        type: string
      page_name:
        type: string
      screen_height:
        type: integer
      screen_width:
        type: integer
      sdk_name:
        type: string
      sdk_version_code:
        type: string
      sdk_version_name:
        type: string
    required:
    - app_name
    - app_version_code
    - app_version_name
    - channel_code
    - device_model
    - device_no
    - event_kv_json
    - event_name
    - imei
    - net_type
    - newevent_type
    - newsession_id
    - os_version_code
    - os_version_name
    - screen_height
    - screen_width
    - sdk_name
    - sdk_version_code
    - sdk_version_name
    type: object
info:
  contact: {}
  license: {}
paths:
  /trailer_api/app/get_new_app:
    post:
      description: 获取最新的 APP 版本信息
      operationId: UPDATE APP
      parameters:
      - description: UPDATE_APP
        in: body
        name: name
        required: true
        schema:
          $ref: '#/definitions/app_service.AppParam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: UPDATE APP
      tags:
      - APP
  /trailer_api/stats/record_device:
    post:
      description: 设备信息上报
      operationId: Record Device
      parameters:
      - description: Device
        in: body
        name: name
        required: true
        schema:
          $ref: '#/definitions/stats_service.Device'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 设备信息上报
      tags:
      - Stats
  /trailer_api/stats/record_sdk_err:
    post:
      description: SDK 错误信息上报
      operationId: Record SdkError
      parameters:
      - description: SdkError
        in: body
        name: name
        required: true
        schema:
          $ref: '#/definitions/stats_service.SdkError'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: SDK 错误信息上报
      tags:
      - Stats
  /trailer_api/stats/record_sdk_event:
    post:
      description: SDK 事件统计   参数：事件 json 数组
      operationId: Insert SdkEvent
      parameters:
      - description: Events
        in: body
        name: name
        required: true
        schema:
          $ref: '#/definitions/stats_service.SdkEvent'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: SDK 事件统计
      tags:
      - Stats
  /trailer_api/trailer/get_trailer_list:
    post:
      description: 获取预告片信息
      operationId: Get TrailerList
      parameters:
      - description: TrailerListParam
        in: body
        name: TrailerListParam
        required: true
        schema:
          $ref: '#/definitions/gredis.TrailerListParam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Get TrailerList
      tags:
      - Trailer
  /trailer_api/trailer/sync_asset:
    post:
      description: 同步 Asset 素材信息
      operationId: Sync Asset
      parameters:
      - description: SyncAsset
        in: body
        name: name
        required: true
        schema:
          $ref: '#/definitions/gredis.Asset'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Sync Asset
      tags:
      - Trailer
swagger: "2.0"
