definitions:
  app.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
  gredis.TrailerListParam:
    type: object
  stats_service.Device:
    properties:
      android_version_code:
        type: string
      android_version_name:
        type: string
      app_name:
        type: string
      app_version_code:
        type: string
      app_version_name:
        type: string
      channel_code:
        type: string
      device_model:
        type: string
      device_name:
        type: string
      device_no:
        type: string
      device_vendor:
        type: string
      ip:
        type: string
      resolution:
        type: string
    required:
    - android_version_code
    - android_version_name
    - app_name
    - app_version_code
    - app_version_name
    - channel_code
    - device_model
    - device_name
    - device_no
    - device_vendor
    - ip
    - resolution
    type: object
  stats_service.ObjSdkEvents:
    properties:
      sdk_events:
        type: string
    required:
    - sdk_events
    type: object
  stats_service.SdkError:
    properties:
      app_name:
        type: string
      app_version_code:
        type: string
      app_version_name:
        type: string
      channel_code:
        type: string
      crash_log:
        type: string
      crash_time:
        type: string
      device_no:
        type: string
      ext:
        type: string
      sdk_name:
        type: string
      sdk_version_code:
        type: string
      sdk_version_name:
        type: string
      user_id:
        type: integer
    required:
    - app_name
    - app_version_code
    - app_version_name
    - channel_code
    - crash_log
    - crash_time
    - device_no
    - sdk_name
    - sdk_version_code
    - sdk_version_name
    type: object
info:
  contact: {}
  license: {}
paths:
  /trailer_api/stats/record_device:
    post:
      description: 设备信息上报
      operationId: Record Device
      parameters:
      - description: Device
        in: body
        name: name
        required: true
        schema:
          $ref: '#/definitions/stats_service.Device'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 设备信息上报
      tags:
      - Device
  /trailer_api/stats/record_sdk_err:
    post:
      description: SDK 错误信息上报
      operationId: Record SdkError
      parameters:
      - description: SdkError
        in: body
        name: name
        required: true
        schema:
          $ref: '#/definitions/stats_service.SdkError'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: SDK 错误信息上报
      tags:
      - SdkError
  /trailer_api/stats/record_sdk_event:
    post:
      description: SDK 事件统计   参数：事件 json 数组
      operationId: Insert SdkEvent
      parameters:
      - description: Events
        in: body
        name: name
        required: true
        schema:
          $ref: '#/definitions/stats_service.ObjSdkEvents'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: SDK 事件统计
      tags:
      - SdkEvent
  /trailer_api/trailer/get_trailers:
    post:
      description: Get TrailerList
      operationId: Get TrailerList
      parameters:
      - description: TrailerListParam
        in: body
        name: TotalRegionUV
        required: true
        schema:
          $ref: '#/definitions/gredis.TrailerListParam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Get TrailerList
      tags:
      - Trailer
swagger: "2.0"
